const productData = [
  {   
    id: '1', 
    nombre:"GFORCE RTX 3080",
    category: "gpu",
    descripcion:"TARJETA GRÁFICA ENVIDIA",
    especificaciones:"MEMORIA DE 16GB",
    imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
    nroserie:"32165488752",
    nromac:"ABC-1235-1215-4545",
    precio:"3500",
    stock:"35",
    minimo:"10",
    preferencia:"1",
    estado:"true",
    idCategoria:"3",
    idMarca:"3",
    idFabricante:"1"
    },
    {   
      id: '2', 
      nombre:"GFORCE RTX 3080",
      category: "scrren",
      descripcion:"TARJETA GRÁFICA ENVIDIA",
      especificaciones:"MEMORIA DE 16GB",
      imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
      nroserie:"32165488752",
      nromac:"ABC-1235-1215-4545",
      precio:"3500",
      stock:"35",
      minimo:"10",
      preferencia:"1",
      estado:"true",
      idCategoria:"3",
      idMarca:"3",
      idFabricante:"1"
      },
      {   
        id: '3', 
        nombre:"GFORCE RTX 3080",
        category: "screen",
        descripcion:"TARJETA GRÁFICA ENVIDIA",
        especificaciones:"MEMORIA DE 16GB",
        imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
        nroserie:"32165488752",
        nromac:"ABC-1235-1215-4545",
        precio:"3500",
        stock:"35",
        minimo:"10",
        preferencia:"1",
        estado:"true",
        idCategoria:"3",
        idMarca:"3",
        idFabricante:"1"
        },
        {   
          id: '4', 
          nombre:"GFORCE RTX 3080",
          category: "mouse",
          descripcion:"TARJETA GRÁFICA ENVIDIA",
          especificaciones:"MEMORIA DE 16GB",
          imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
          nroserie:"32165488752",
          nromac:"ABC-1235-1215-4545",
          precio:"3500",
          stock:"35",
          minimo:"10",
          preferencia:"1",
          estado:"true",
          idCategoria:"3",
          idMarca:"3",
          idFabricante:"1"
          },
          {   
            id: '5', 
            nombre:"GFORCE RTX 3080",
            category: "motherboard",
            descripcion:"TARJETA GRÁFICA ENVIDIA",
            especificaciones:"MEMORIA DE 16GB",
            imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
            nroserie:"32165488752",
            nromac:"ABC-1235-1215-4545",
            precio:"3500",
            stock:"35",
            minimo:"10",
            preferencia:"1",
            estado:"true",
            idCategoria:"3",
            idMarca:"3",
            idFabricante:"1"
            },
            {  
              id: '6', 
              nombre:"GFORCE RTX 3080",    
              category: "gpu",
              descripcion:"TARJETA GRÁFICA ENVIDIA",
              especificaciones:"MEMORIA DE 16GB",
              imagen:"https://hiraoka.com.pe/media/mageplaza/blog/post/t/a/tarjeta_grafica-que_es_y_como_funciona.jpg",
              nroserie:"32165488752",
              nromac:"ABC-1235-1215-4545",
              precio:"3500",
              stock:"35",
              minimo:"10",
              preferencia:"1",
              estado:"true",
              idCategoria:"3",
              idMarca:"3",
              idFabricante:"1"
              },
];
export default productData;